services:
  # The Backend Web Service
  - type: web
    name: master-backend-tet2
    runtime: docker
    repo: https://github.com/sown1812/Master-English
    plan: free
    region: singapore # Optional, but good for latency
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        fromDatabase:
          name: master-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: master-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: master-db
          property: password
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false # Prompts the user to input this value on creation

databases:
  # The PostgreSQL Database
  - name: master-db
    plan: free
    region: singapore
    databaseName: master_db
    user: master_user

version: "1"
